import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { GRANDMOTHER_RECIPES } from '../data/GrandmotherRecipes';
import { INTERNATIONAL_RECIPES } from '../data/InternationalRecipes';

const PALATE_NAMES = {
  general: 'Others',
  punjab: 'Punjab',
  gujarat: 'Gujarat',
  maharashtra: 'Maharashtra',
  kolkata: 'West Bengal',
  odisha: 'Odisha',
  tamilnadu: 'Tamil Nadu',
  kerala: 'Kerala'
};

const DAYS = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'];
const MEALS = [
  { key: 'breakfast', label: '🍳 Breakfast' },
  { key: 'lunch', label: '🍽️ Lunch' },
  { key: 'snack', label: '☕ Evening Snack' },
  { key: 'dinner', label: '🌙 Dinner' }
];

export default function WeeklyPlanner() {
  const { state, dispatch } = useApp();
  const { profile = {}, weeklyPlan = {} } = state;
  
  // Get short code for current day (e.g. "MON")
  const currentShortDay = new Date().toLocaleDateString('en-US', { weekday: 'short' }).toUpperCase();
  const [activeDay, setActiveDay] = useState(currentShortDay === 'MON' || DAYS.includes(currentShortDay) ? currentShortDay : 'MON');
  const [selectedRecipe, setSelectedRecipe] = useState(null);
  
  // State for printable PDF modal
  const [showPdfModal, setShowPdfModal] = useState(false);

  // Dynamic swap logic using actual region/diet matched recipe pool
  const handleSwapMeal = (mealType) => {
    const isGujarati = (profile?.regionalPalate || 'general').toLowerCase() === 'gujarat';
    const isStrictVeg = isGujarati || !(profile?.dietType || 'Vegetarian 🌱').toLowerCase().includes('non-');

    const filterVeg = (list) => isStrictVeg ? list.filter(r => r.isVegetarian) : list;
    
    const pool = [...filterVeg(GRANDMOTHER_RECIPES), ...filterVeg(INTERNATIONAL_RECIPES)];
    const filteredPool = pool.filter(r => r.name !== weeklyPlan[activeDay]?.[mealType]?.name);

    if (filteredPool.length === 0) return;

    // Pick random alternative
    const randomIndex = Math.floor(Math.random() * filteredPool.length);
    const chosenAlternative = filteredPool[randomIndex];

    dispatch({
      type: 'SWAP_MEAL',
      payload: {
        day: activeDay,
        mealType,
        newMeal: {
          id: chosenAlternative.id,
          name: chosenAlternative.name,
          isVegetarian: chosenAlternative.isVegetarian,
          category: mealType,
          region: chosenAlternative.region || 'Indian',
          ingredients: chosenAlternative.ingredients || [],
          steps: chosenAlternative.steps || []
        }
      }
    });
  };

  // WhatsApp Grocery Shopping List Generator (Innovation 6)
  const handleShareToWhatsApp = () => {
    let listText = `🏡 *HomeChef AI - ${profile.familyName ? (profile.familyName.toLowerCase().includes('family') ? profile.familyName : `${profile.familyName} Family`) : 'My Family'} Grocery List* 🏡\n`;
    listText += `🗓️ _Week Plan: ${DAYS.join(' | ')}_\n\n`;

    const allIngredients = new Set();
    
    // Aggregate ingredients from all main meals in the weekly plan
    DAYS.forEach(day => {
      ['lunch', 'dinner'].forEach(mealKey => {
        const meal = weeklyPlan[day]?.[mealKey];
        if (meal && meal.ingredients) {
          meal.ingredients.slice(0, 3).forEach(ing => allIngredients.add(ing)); // Top ingredients to keep message compact
        }
      });
    });

    if (allIngredients.size === 0) {
      listText += `- Aata / Flour (Staple)\n- Rice (Staple)\n- Ghee / Cooking oil\n- Onions & Potatoes\n`;
    } else {
      Array.from(allIngredients).forEach(ing => {
        listText += `▪️ ${ing}\n`;
      });
    }

    listText += `\n🤖 _Generated by HomeChef AI - Rasoi ka Saathi_`;
    
    const encodedText = encodeURIComponent(listText);
    const whatsappUrl = `https://api.whatsapp.com/send?text=${encodedText}`;
    window.open(whatsappUrl, '_blank');
  };

  // Trigger browser print dialog for the custom print CSS styles
  const handlePrint = () => {
    window.print();
  };

  return (
    <div style={styles.scrollContainer} className="no-scrollbar animate-fade-in">
      {/* Page Title */}
      <div style={styles.header}>
        <h1 className="text-serif" style={styles.title}>Planner</h1>
        <p style={styles.subtitle}>Tap day. Swap or save with archetype flavor.</p>
      </div>

      {/* Horizontal Day Selector */}
      <div style={styles.daySelector} className="no-scrollbar">
        {DAYS.map(day => {
          const isActive = day === activeDay;
          const isToday = day === currentShortDay;
          return (
            <button
              key={day}
              style={{
                ...styles.dayBtn,
                background: isActive ? 'linear-gradient(135deg, #E8692A 0%, #C4501A 100%)' : '#fff',
                color: isActive ? '#fff' : '#1A0E08',
                borderColor: isToday ? '#E8692A' : 'rgba(74, 44, 26, 0.1)',
                borderWidth: isToday ? '2px' : '1px'
              }}
              onClick={() => setActiveDay(day)}
            >
              <span style={styles.dayName}>{day}</span>
              {isToday && <span style={{ ...styles.todayDot, color: isActive ? '#fff' : '#E8692A' }}>•</span>}
            </button>
          );
        })}
      </div>

      {/* Selected Day's Meals */}
      <div style={styles.mealsContainer}>
        {MEALS.map(meal => {
          const plannedMeal = weeklyPlan[activeDay]?.[meal.key] || { name: 'Simple Healthy Thali' };
          return (
            <div key={meal.key} style={styles.mealCard} className="glass-card animate-pop">
              <div style={styles.mealHeader}>
                <span style={styles.mealLabel}>{meal.label.toUpperCase()}</span>
                <span style={{ ...styles.mealDietTag, color: plannedMeal.isVegetarian ? '#0D6E4E' : '#C0392B' }}>
                  {plannedMeal.isVegetarian ? '🌱 VEG' : '🍗 NON-VEG'}
                </span>
              </div>

              <div style={styles.mealContent}>
                <h3 style={styles.mealName}>{plannedMeal.name}</h3>
                {plannedMeal.region && <span style={styles.mealRegion}>{plannedMeal.region} Style</span>}
              </div>

              <div style={styles.actionRow}>
                {plannedMeal.steps && plannedMeal.steps.length > 0 && (
                  <button style={styles.actionBtn} onClick={() => setSelectedRecipe(plannedMeal)}>
                    View
                  </button>
                )}
                <button style={styles.actionBtn} onClick={() => handleSwapMeal(meal.key)}>
                  Swap
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {/* Action Buttons Row */}
      <div style={styles.shareContainer}>
        <button style={{ ...styles.shareBtn, marginBottom: '12px' }} className="btn-primary" onClick={handleShareToWhatsApp}>
          Share List
        </button>
        <button style={styles.printTriggerBtn} onClick={() => setShowPdfModal(true)}>
          Print Plan
        </button>
      </div>

      {/* Recipe Detail Modal */}
      {selectedRecipe && (
        <div style={styles.modalOverlay} className="animate-fade-in">
          <div style={styles.modalContent} className="glass-card animate-slide-up">
            <h2 className="text-serif" style={styles.modalTitle}>{selectedRecipe.name}</h2>
            <span style={styles.modalRegion}>{selectedRecipe.region} Cuisine • traditional</span>
            
            <div style={styles.modalAccordion}>
              <h4 style={styles.accordionHeader}>📝 Ingredients</h4>
              <ul style={styles.ingredientsList}>
                {selectedRecipe.ingredients.map((ing, i) => <li key={i}>{ing}</li>)}
              </ul>

              <h4 style={{ ...styles.accordionHeader, marginTop: '16px' }}>👩‍🍳 Steps</h4>
              <ol style={styles.stepsList}>
                {selectedRecipe.steps.map((st, i) => <li key={i}>{st}</li>)}
              </ol>
            </div>

            <button style={styles.closeModalBtn} onClick={() => setSelectedRecipe(null)}>Done</button>
          </div>
        </div>
      )}

      {/* 🖨️ Printable PDF Modal Overlay (Agent C printable layout) */}
      {showPdfModal && (
        <div style={styles.modalOverlay} className="animate-fade-in no-print-overlay">
          <div style={styles.pdfModalContent} className="glass-card animate-slide-up">
            
            {/* Action buttons at top (no-print) */}
            <div style={styles.pdfActionsRow} className="no-print">
              <button style={styles.pdfPrintBtn} onClick={handlePrint}>
                🖨️ Print / Save as PDF
              </button>
              <button style={styles.pdfCloseBtn} onClick={() => setShowPdfModal(false)}>
                ✕ Close Preview
              </button>
            </div>

            {/* Printable Area starts here */}
            <div className="pdf-body-print-container" style={styles.pdfPrintContainer}>
              <div className="pdf-print-header" style={styles.pdfHeader}>
                <h1 className="text-serif" style={styles.pdfLogo}>🥘 HomeChef AI v2</h1>
                <p style={styles.pdfSubtitle}>
                  Weekly Thali Meal Plan for the <strong>{profile.familyName ? (profile.familyName.toLowerCase().includes('family') ? profile.familyName : `${profile.familyName} Family`) : 'My Family'}</strong>
                </p>
                <span style={styles.pdfDetails}>
                  Cuisine Palate: {(PALATE_NAMES[profile.regionalPalate] || profile.regionalPalate).toUpperCase()} • Diet type: {profile.dietType}
                </span>
              </div>

              {/* Weekly Menu Grid Table */}
              <table className="pdf-print-grid" style={styles.pdfTable}>
                <thead>
                  <tr>
                    <th style={styles.tableTh}>Day</th>
                    <th style={styles.tableTh}>🍳 Breakfast</th>
                    <th style={styles.tableTh}>🍽️ Lunch</th>
                    <th style={styles.tableTh}>☕ Snack</th>
                    <th style={styles.tableTh}>🌙 Dinner</th>
                  </tr>
                </thead>
                <tbody>
                  {DAYS.map(day => (
                    <tr key={day}>
                      <td style={styles.tableTd}><strong>{day}</strong></td>
                      <td style={styles.tableTd}>{weeklyPlan[day]?.breakfast?.name || 'Simple Healthy Thali'}</td>
                      <td style={styles.tableTd}>
                        <strong>{weeklyPlan[day]?.lunch?.name || 'Simple Healthy Thali'}</strong>
                        {weeklyPlan[day]?.lunch?.region && <span style={styles.tableRegion}> ({weeklyPlan[day]?.lunch?.region})</span>}
                      </td>
                      <td style={styles.tableTd}>{weeklyPlan[day]?.snack?.name || 'Simple Healthy Thali'}</td>
                      <td style={styles.tableTd}>
                        <strong>{weeklyPlan[day]?.dinner?.name || 'Simple Healthy Thali'}</strong>
                        {weeklyPlan[day]?.dinner?.region && <span style={styles.tableRegion}> ({weeklyPlan[day]?.dinner?.region})</span>}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>

              <div style={styles.pdfFooter}>
                <p>Generated by HomeChef AI - Rasoi ka Saathi. Plan healthy. Eat traditional.</p>
              </div>
            </div>

          </div>
        </div>
      )}
    </div>
  );
}

const styles = {
  scrollContainer: {
    padding: '20px',
    overflowY: 'auto',
    flex: 1,
    background: '#FDF8F2'
  },
  header: {
    marginBottom: '20px'
  },
  title: {
    fontSize: '28px',
    color: '#1A0E08',
    margin: 0
  },
  subtitle: {
    fontSize: '14px',
    color: '#7A5540'
  },
  daySelector: {
    display: 'flex',
    gap: '8px',
    overflowX: 'auto',
    paddingBottom: '12px',
    marginBottom: '24px'
  },
  dayBtn: {
    flex: '0 0 60px',
    height: '60px',
    borderRadius: '16px',
    border: '1px solid',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontFamily: 'Outfit, sans-serif',
    fontWeight: '700',
    transition: 'all 0.2s ease'
  },
  dayName: {
    fontSize: '14px'
  },
  todayDot: {
    fontSize: '14px',
    lineHeight: '6px',
    marginTop: '2px'
  },
  mealsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px'
  },
  mealCard: {
    padding: '20px',
    background: '#fff',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px'
  },
  mealHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '11px',
    fontWeight: '800',
    letterSpacing: '0.5px'
  },
  mealLabel: {
    color: '#E8692A'
  },
  mealDietTag: {
    fontWeight: '800'
  },
  mealContent: {
    textAlign: 'left'
  },
  mealName: {
    fontSize: '18px',
    fontWeight: '800',
    color: '#1A0E08'
  },
  mealRegion: {
    display: 'inline-block',
    fontSize: '11px',
    fontWeight: '700',
    color: '#0D6E4E',
    background: '#E8F5F0',
    padding: '2px 6px',
    borderRadius: '10px',
    marginTop: '4px'
  },
  actionRow: {
    display: 'flex',
    gap: '10px',
    borderTop: '1px solid rgba(74, 44, 26, 0.08)',
    paddingTop: '12px',
    marginTop: '4px'
  },
  actionBtn: {
    flex: 1,
    background: '#F9F1E5',
    color: '#4A2C1A',
    border: '1px solid rgba(74, 44, 26, 0.1)',
    borderRadius: '10px',
    padding: '10px',
    fontSize: '13px',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.2s ease'
  },
  shareContainer: {
    marginTop: '28px',
    marginBottom: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px'
  },
  shareBtn: {
    width: '100%'
  },
  printTriggerBtn: {
    width: '100%',
    background: '#FEF3DC',
    color: '#C4501A',
    border: '1px solid rgba(232, 105, 42, 0.25)',
    borderRadius: '14px',
    padding: '14px',
    fontSize: '15px',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.2s ease'
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(26, 14, 8, 0.45)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-end',
    zIndex: 99
  },
  modalContent: {
    width: '100%',
    maxHeight: '85%',
    background: '#FDF8F2',
    borderTopLeftRadius: '28px',
    borderTopRightRadius: '28px',
    padding: '28px 28px 90px 28px', // Safety padding safety-overlay fix
    overflowY: 'auto'
  },
  pdfModalContent: {
    width: '100%',
    maxHeight: '90%',
    background: '#FFFDF9',
    borderTopLeftRadius: '28px',
    borderTopRightRadius: '28px',
    padding: '24px 24px 90px 24px', // Safety padding safety-overlay fix
    overflowY: 'auto'
  },
  modalTitle: {
    fontSize: '28px',
    color: '#1A0E08'
  },
  modalRegion: {
    display: 'inline-block',
    fontSize: '13px',
    color: '#C4501A',
    fontWeight: '700',
    marginTop: '4px',
    marginBottom: '20px'
  },
  modalAccordion: {
    textAlign: 'left',
    marginBottom: '24px'
  },
  accordionHeader: {
    fontSize: '16px',
    fontWeight: '800',
    color: '#1A0E08',
    borderBottom: '1px solid rgba(74, 44, 26, 0.1)',
    paddingBottom: '8px',
    marginBottom: '10px'
  },
  ingredientsList: {
    listStyleType: 'disc',
    paddingLeft: '20px',
    fontSize: '14px',
    lineHeight: '1.6',
    color: '#4A2C1A'
  },
  stepsList: {
    paddingLeft: '20px',
    fontSize: '14px',
    lineHeight: '1.6',
    color: '#4A2C1A'
  },
  closeModalBtn: {
    width: '100%',
    background: 'linear-gradient(135deg, #E8692A 0%, #C4501A 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '14px',
    padding: '14px',
    fontSize: '15px',
    fontWeight: '700',
    cursor: 'pointer'
  },
  
  // PDF Printable Modal Styles
  pdfActionsRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '20px',
    gap: '12px'
  },
  pdfPrintBtn: {
    flex: 1,
    background: 'linear-gradient(135deg, #0D6E4E 0%, #1B7A4E 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    padding: '12px',
    fontSize: '14px',
    fontWeight: '700',
    cursor: 'pointer'
  },
  pdfCloseBtn: {
    background: '#F9F1E5',
    color: '#4A2C1A',
    border: '1px solid rgba(74, 44, 26, 0.1)',
    borderRadius: '10px',
    padding: '12px 16px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer'
  },
  pdfPrintContainer: {
    textAlign: 'left',
    background: '#FFFDF9',
    padding: '12px'
  },
  pdfHeader: {
    borderBottom: '2px solid #1A0E08',
    paddingBottom: '12px',
    marginBottom: '20px'
  },
  pdfLogo: {
    fontSize: '24px',
    color: '#1A0E08'
  },
  pdfSubtitle: {
    fontSize: '14px',
    color: '#4A2C1A',
    marginTop: '4px'
  },
  pdfDetails: {
    fontSize: '11px',
    color: '#7A5540',
    fontWeight: '700',
    display: 'block',
    marginTop: '4px'
  },
  pdfTable: {
    width: '100%',
    borderCollapse: 'collapse',
    marginTop: '16px'
  },
  tableTh: {
    background: '#F9F1E5',
    border: '1px solid #7A5540',
    padding: '8px',
    fontSize: '12px',
    fontWeight: '700',
    textAlign: 'left'
  },
  tableTd: {
    border: '1px solid #7A5540',
    padding: '8px',
    fontSize: '12px',
    verticalAlign: 'top',
    lineHeight: '1.4'
  },
  tableRegion: {
    fontSize: '10px',
    color: '#0D6E4E',
    fontStyle: 'italic'
  },
  pdfFooter: {
    marginTop: '24px',
    borderTop: '1px dashed rgba(74, 44, 26, 0.15)',
    paddingTop: '12px',
    fontSize: '11px',
    color: '#7A5540',
    textAlign: 'center'
  }
};
